services:
  api:
    build:
      context: .
      secrets:
        - NODE_AUTH_TOKEN

  worker:
    build:
      context: ../hookops-worker
      secrets:
        - NODE_AUTH_TOKEN

secrets:
  NODE_AUTH_TOKEN:
    environment: NODE_AUTH_TOKEN
