services:
  api:
    build:
      context: .
      args:
        NODE_AUTH_TOKEN: ${NODE_AUTH_TOKEN}

  worker:
    build:
      context: ../hookops-worker
      args:
        NODE_AUTH_TOKEN: ${NODE_AUTH_TOKEN}
